### ISSUE TITLE
How to manage/archive old sftp dumps

### ISSUE THREAD

**Issue by relaxing** [tulibraries/cob_datapipeline#30]
Currently this is a manual process, since the entire Alma sftp export is manual anyway.
Do we want to automate it with logrotate (my preference)? Or have an airflow task do it?
And how many do we keep? (Disk space vs ability to look back considerations.)
Keep in mind we may greatly increase the frequency of full reindexing.

**Comment by cmharlow** [comment]
Related to: https://github.com/tulibraries/grittyOps/issues/58
