### ISSUE TITLE
Improve Alma OAI Endpoint

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/cob_datapipeline#45]
- [x] Confirm Alma OAI's `last_updated` field(s) per record in the `ADM` enhanced field accurately reflects the `last_updated` date of the bibliographic record, holdings, and possibly items. A test set of these records, with new enrichment added, is available on the FTP server (file name test_alma_bibs_2019041016_11157338920003811_new.1.xml)
- [x] Use an updated traject mapping in tul_cob; see https://github.com/tulibraries/tul_cob/issues/1113
- [x] Shift OAI harvest time ranges to cover possible dropping of records between Alma OAI publication jobs (every 6 hours)

**Comment by relaxing** [comment]
Admin can change frequency of OAI publishing, exacerbating the harvest time range issue. 
I believe we should change the last update date logic to not update when we retrieve zero records.

**Comment by cmharlow** [comment]
Step 2 completed by tulibraries/tul_cob#1153 ; awaiting deployment
