### ISSUE TITLE
bash vs bashrc vs profile (interactive & login or not shells) run by BashOperators

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/cob_datapipeline#54]
When the bashoperator runs a bash script, even as user airflow, it runs bash as a non-interactive, non-login shell; thus, the bash script cannot access rbenv (or any of the airflow users bash environment setup). 

For now, this is temporarily fixed by sourcing bashrc in the bash scripts themselves; in the future, what should we do to fix this? `bash -l` for the BashOperator? Is there a missing profile to be loaded?

**Comment by dkinzer** [comment]
I looked into this a bit...
I'm not sure it will be possible to run bash as a login process without overriding or patching airflow: 

https://github.com/apache/airflow/blob/master/airflow/operators/bash_operator.py#L121

I also learned that there is a `BASH_ENV` environment that should be a path to a file that bash will run for all non-interactive processes.  However when I tried setting it on my local it seemed to cause an infinite loop of bash processes.... (not sure if I was just doing it wrong or something)...

I learned about `BASH_ENV` here:
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html
