### ISSUE TITLE
Change tul_cob checkout to happen within DAG / tasks

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/cob_datapipeline#77]

**Comment by dkinzer** [comment]
We've updated az index use cob_az_index repo and we combine checkout and ingest process into one task so that we can now run that dag in a multi processor dag setup without worry.

**Comment by cmharlow** [comment]
This should be covered in all the SC DAGs; @dkinzer do you think we should wait to close until all the existing DAGs still relying on this are removed?

**Comment by dkinzer** [comment]
Hmmm... I think since issue is fixed int SC dags and we are definitely going to move to SC, it's OK to close this.
