### ISSUE TITLE
Refactor harvest tasks to allow for no ALMA OAI harvests

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/cob_datapipeline#82]
The current OAI harvest task, `almaoai_harvest.py`, has a lot of baked in assumptions about the data that is coming in that block it from being reused for non Alma OAI feeds.

This includes, but is not limited to:

- wrapping the data in a collection tag
- Sickle harvest arguments

The harvest task should be refactored into a more generic OAI harvester, allowing extra steps to be added via parametrization

**Comment by cmharlow** [comment]
Work on this side is in #91 ; moving this issue now to tulibraries/tulflow (which tulibraries/funcake_dags is calling for shared code bits)
