### ISSUE TITLE
Create DAG for DPLA harvesting

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/cob_datapipeline#83]
Create a DAG that follows the patterns of the [ALMA OAI harvesting dag](https://github.com/tulibraries/cob_datapipeline/blob/qa/tul_cob_pipeline_dag.py) to harvest data from Combine's OAI endpoint and sends it to Solr for Blacklight.

Blocked by #82

**Comment by cmharlow** [comment]
Few infra questions:
- do you want DPLA work in the tul_cob dag repo? airflow role + playbook were written to handle pulling in multiple repos for DAG groupings
- unlike Alma's, Combine's OAI endpoints don't require special network shit, yeah?
- which Solr(s) and Blacklight instance(s) are you needing here (worried above overloading tul cob solr & lack of time / support in getting solrcloud up for this & lack of existing knowledge on how to adequately replication existing solr nodes that won't fail)

**Comment by cmharlow** [comment]
Moving to tulibraries/funcake_dags
