### ISSUE TITLE
Create Web Content Reindex DAG

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/cob_datapipeline#86]
We need a DAG to hit API endpoints from the new website and push that data into solr.

**Comment by dkinzer** [comment]
@bibliotechy we have an issue on the jira for this sprint regarding this (BL-925).  Would it be possible for @sensei100 and I to take this over as we want to keep it in line with how we've implemented the az dag using cob_az_index.  We are planning on creating an equivalent cob_web_index repo/app to use both in the dag and in local web development and whatnot.

**Comment by bibliotechy** [comment]
@dkinzer
